# Generated by Django 4.2.10 on 2025-07-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_turno_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='telefono',
            field=models.CharField(default='desconocido', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turno',
            name='tipo',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
