# Generated by Django 4.2.10 on 2025-07-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_turno_telefono_turno_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='tipo',
        ),
        migrations.AddField(
            model_name='turno',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
    ]
